trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.TeamsAI.csproj'

steps:
- task: UseDotNet@2
  inputs:
    version: '6.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(projectPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
  displayName: 'ESRP Signing - strong name (CP-233863-SN)'
  inputs:
    ConnectedServiceName: 'ESRP Code Signing Connection 2020a'
    FolderPath: '$(projectPath)'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameSign",
             "parameters": [],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-233863-SN",
             "operationSetCode": "StrongNameVerify",
             "parameters": [],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
     
    SessionTimeout: 20

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
  displayName: 'ESRP Signing - authenticode (CP-230012)'
  inputs:
    ConnectedServiceName: 'ESRP Code Signing Connection 2020a'
    FolderPath: '$(projectPath)'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
            "keyCode": "CP-230012",
            "operationSetCode": "SigntoolSign",
            "parameters": [
            {
                "parameterName": "OpusName",
                "parameterValue": "Microsoft"
            },
            {
                "parameterName": "OpusInfo",
                "parameterValue": "http://www.microsoft.com"
            },
            {
                "parameterName": "PageHash",
                "parameterValue": "/NPH"
            },
            {
                "parameterName": "FileDigest",
                "parameterValue": "/fd \"SHA256\""
            },
            {
                "parameterName": "TimeStamp",
                "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
            ],
            "toolName": "sign",
            "toolVersion": "1.0"
        },
        {
            "keyCode": "CP-230012",
            "operationSetCode": "SigntoolVerify",
            "parameters": [ ],
            "toolName": "sign",
            "toolVersion": "1.0"
        }
     ]
    SessionTimeout: 20

- task: NuGetCommand@2
  displayName: 'NuGet Pack'
  inputs:
    command: pack
    packagesToPack: '$(projectPath)'
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Packages

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'Azure NuGet Push'
  inputs:
    command: push
    publishVstsFeed: 'SDK_v4/Teams'
    allowPackageConflicts: true
    includeNugetOrg: true

- script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)/**/*.nupkg --api-key $(nugetApiKey) --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols'
  displayName: 'NuGet Push'
