trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - js

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node'

- script: 'npm i -g yarn'
  displayName: 'Install Yarn'

- script: 'yarn'
  workingDirectory: 'js'
  displayName: 'Install Dependencies'

- script: 'yarn build'
  workingDirectory: 'js'
  displayName: 'Build'

- script: 'yarn test'
  workingDirectory: 'js'
  displayName: 'Test'

- script: 'yarn lint'
  workingDirectory: 'js'
  displayName: 'Lint'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: js/packages/teams-ai/*
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Packages

- task: Npm@1
  displayName: 'Publish'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: 'Github_Pipelines/Teams'
